#cloud-config

package_update: true

packages:
 - NetworkManager
 - httpd-tools
 - openssh-server
 - wget
 - git
 - net-tools
 - bind-utils
 - yum-utils
 - iptables-services
 - bridge-utils
 - bash-completion
 - kexec-tools
 - sos
 - psacct
 - atomic-openshift-utils
 - docker-1.13.1
 - lvm2

growpart:
   mode: off

runcmd:
 - [ systemctl, enable, sshd ]
 - [ systemctl, start, sshd ]
 - [ parted, "/dev/vda", print ]
 - [ parted, "/dev/vda", mkpart, primary, ext2, "50GB", "100%" ]
 - [ parted, "/dev/vda", set, "2", lvm, on ]
 - [ growpart, "/dev/vda", "1" ] 
 - [ partx, "--update", "/dev/vda" ]
 - [ xfs_growfs, "/dev/vda1" ]
 - [ pvcreate, "/dev/vda2" ]
 - [ vgcreate, "docker-vg", "/dev/vda2" ]
 - [ parted, "/dev/vda", print ]
 - [ bash, "-c", "echo VG=docker-vg > /etc/sysconfig/docker-storage-setup" ]
 - [ systemctl, enable, docker.service ]
 - [ systemctl, start, docker.service ]
